name: Deploy Python Web App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/deploy-app.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-west-2
          ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/python-web-app"
          
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker Image
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-west-2
          ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/python-web-app"

          docker build -t python-web-app .
          docker tag python-web-app:latest $ECR_REPO:latest

      - name: Push Docker Image to ECR
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-west-2
          ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/python-web-app"

          docker push $ECR_REPO:latest

      - name: Update Kubernetes Deployment
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-west-2
          ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/python-web-app"
          sed -i "s|<ECR_REPO>|$ECR_REPO|g" terraform/k8s-deployment.yaml


      - name: Apply Kubernetes ConfigMaps
        run: kubectl apply -f kubernetes/aws-auth-configmap.yaml
           
      - name: Apply Kubernetes Deployment
        run: |
          aws eks update-kubeconfig --name python-web-app-cluster --region us-west-2
          kubectl apply -f terraform/k8s-deployment.yaml
          kubectl apply -f terraform/k8s-service.yaml
